### PR TITLE
Remove InformationEntity, Document, Method from core-im-source.yaml

### PR DESCRIPTION
**Pull request by mbrush**
Removed `InformationEntity`, `Method`, and `Document` classes (and moved them back into va-spec core-im-source - because `InformationEntity` is no longer referenced in gks-commons `RecordMetadata` and `Contribution classes`, and with `InformationEntity` gone, `Document` and `Method` are also not referenced by any gks-commons properties.  So there is no need to keep them in common, unless we identify broader use cases outside of va-spec for these classes.

Also, changed the `computer` value in the agentType enum to `software`.

### CODE REVIEW

**Comment by larrybabb** [comment]
@mbrush This PR has an issue. If we remove `Activity` then `Contribution` will fail because it inherits from it. But if we leave `Activity` then we need to leave `Method` since it is referenced in the `specifiedBy` attribute. I'm going to pass this over for now until I hear back from you on how you'd like to proceed.

**Review by larrybabb — CHANGES_REQUESTED** [review]
@mbrush This PR has an issue. If we remove Activity then Contribution will fail because it inherits from it. But if we leave Activity then we need to leave Method since it is referenced in the specifiedBy attribute. I'm going to pass this over for now until I hear back from you on how you'd like to proceed.

**Comment by mbrush** [comment]
Yes, good catch Larry.  I don’t see a perfect simple solution for this, so here is what I am thinking. 
 
For now let's keep `Activity` and `Contribution` in the va-spec core-im . . . and `RecordMetadata` as well since it references Contributions.  This is the simplest short term fix - and will be fine given that these classes will not be used outside of va-spec profiles in the foreseeable future. 
 
Longer term however, this does make me reconsider this idea of moving **ALL** of the va-core-im content into gks-commons - and having this be the place where the full domain agnostic SEPIO-based information model lives.  I do see some value in this:
- this design would avoid issues related to inheritance dependencies that keep arising, 
- having everything in a single repo would simplify accessibility and maintenance of this core-im.
- not tying this content to the va-spec specifically would facilitate application of the core-im to use cases where 'provenanced' knowledge statements about things besides variants are needed - e.g. SA statements about sequencer features, or statements about diseases or genes that may be useful as evidence for variant classifications in representing full ACMG-based provenance.
 
A consequence of this move would be that the va-spec repo would house only standard VA Profiles for specific types of Statements and Study Results - which kind of makes sense, as these are the va models people will be implementing for their data. 
 
A personal concern with this is that I don’t want to lose control over how the core-im evolves - and ability to ensure it stays aligned with VA-SEPIO principles and patterns. Javi and I currently have authority to do this with the core-im in the va-spec repo, and I would want to maintain this authority if things move into gks-commons.  
 
But for now, if you are ok with the *short term* fix above - I can go ahead and make / update the relevant PRs to push `Activity`, `Contribution`, and `RecordMetadata` back into the va-core im where they started out.  This will get us where we need to be for our upcoming releases.  
 
We can keep stewing about this idea of moving all core-im content under gks-common. But I am not comfortable making such significant change right now - given that the minimal fix above will be sufficient for the foreseeable future.  And if/when we do decide to move everything into commons - it shouldn’t be a big lift technically for us, or conceptually for users to understand.

**Comment by larrybabb** [comment]
@mbrush I understand your perspective and think this is a reasonable short-term plan. I do agree with moving the core-im to a dedicated repo (gks-common) as soon as you are comfortable with that.  For now I will remove any plans to utilize `RecordMetaData` in VRS and Cat-VRS, since I haven't actually gotten to that implementation yet. I can just use extensions for the time being.

**Comment by larrybabb** [comment]
closing this since PR #38 takes its place to complete the intended outcome.

**Pull request closed without merging**
